{"name": "test_guest_can_go_to_login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home", "trace": "E   FileNotFoundError: [WinError 2] Не удается найти указанный файл\n\nDuring handling of the above exception, another exception occurred:\nE   selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home"}, "start": 1637689240618, "stop": 1637689240618, "uuid": "7fc33162-2727-4d2a-87f1-c53f6bee7c46", "historyId": "ce89454eb32d81da7abe3d78f79293b7", "testCaseId": "afba63ba4ada9a3044b9179f4835c21a", "fullName": "test_login_page#test_guest_can_go_to_login_page", "labels": [{"name": "tag", "value": "need_review"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "LAPTOP-Q8IQHMO1"}, {"name": "thread", "value": "28536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_page"}]}